server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


#server:
#  port: 8761
#
#spring:
#  profiles:
#    active: dev
#  application:
#    name: @pom.artifactId@

#security:
#  basic:
#    enabled: true
#  user:
#    name: root
#    password: root